#!/bin/sh
# A script that copies all currently changing entries in portfolio
cd;
cd bin;
cp * ../Documents/Portfolio/Portfolio/Scripts;
cd;
cd Documents/Portfolio/Portfolio;
cp /var/www/html/Mymap/* Mymap;
git add *;
git commit * -m"$1";
git push;
