#!/bin/sh
# A script that copies all currently changing entries in portfolio
cd;
cd bin;
cp * ../Documents/Portfolio/Portfolio/Scripts;
cd;
cd Documents/Portfolio/Portfolio;
cp /var/www/html/Mymap/*.php Mymap;
cp ~/Documents/MITCOP/android/EventFinder3/app/src/main/java/mitcop/eventfinder/* EventFinder;
git add *;
git commit * -m"$1";
git push;
